// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Authors documents
 */
interface AuthorsDocumentData {
  /**
   * Name field in *Authors*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Authors*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: https://linkedin.com/in/neeshsamsi
   * - **API ID Path**: authors.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkToMediaField;
}

/**
 * Authors document from Prismic
 *
 * - **API ID**: `authors`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AuthorsDocumentData>,
    "authors",
    Lang
  >;

/**
 * Content for Blog Posts documents
 */
interface BlogPostsDocumentData {
  /**
   * Cover Image field in *Blog Posts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Title field in *Blog Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: How to Land Your Dream Internship: A Guide for Law Students
   * - **API ID Path**: blog_posts.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Author field in *Blog Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"authors">;

  /**
   * Summary field in *Blog Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  summary: prismic.KeyTextField;

  /**
   * Post Content field in *Blog Posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Your blog post goes here
   * - **API ID Path**: blog_posts.post_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  post_content: prismic.RichTextField;
}

/**
 * Blog Posts document from Prismic
 *
 * - **API ID**: `blog_posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostsDocumentData>,
    "blog_posts",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;

  /**
   * Featured Post field in *Home*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.featured_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_post: prismic.ContentRelationshipField<"blog_posts"> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Site Settings → Email Addresses*
 */
export interface SiteSettingsDocumentDataEmailAddressesItem {
  /**
   * Email field in *Site Settings → Email Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: contactemail@gmail.com
   * - **API ID Path**: site_settings.email_addresses[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Item in *Site Settings → Phone Numbers*
 */
export interface SiteSettingsDocumentDataPhoneNumbersItem {
  /**
   * Phone Number field in *Site Settings → Phone Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.phone_numbers[].phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;
}

/**
 * Content for Site Settings documents
 */
interface SiteSettingsDocumentData {
  /**
   * LinkedIn URL field in *Site Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://linkedin.com/in/neeshsamsi
   * - **API ID Path**: site_settings.linkedin_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_url: prismic.LinkField;

  /**
   * Instagram URL field in *Site Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://instagram.com/neeshsamsi
   * - **API ID Path**: site_settings.instagram_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_url: prismic.LinkField;

  /**
   * Email Addresses field in *Site Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.email_addresses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  email_addresses: prismic.GroupField<
    Simplify<SiteSettingsDocumentDataEmailAddressesItem>
  >;

  /**
   * Phone Numbers field in *Site Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.phone_numbers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  phone_numbers: prismic.GroupField<
    Simplify<SiteSettingsDocumentDataPhoneNumbersItem>
  >;
}

/**
 * Site Settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteSettingsDocumentData>,
    "site_settings",
    Lang
  >;

type SubmissionGuidelinesDocumentDataSlicesSlice = never;

/**
 * Content for Submission Guidelines documents
 */
interface SubmissionGuidelinesDocumentData {
  /**
   * Slice Zone field in *Submission Guidelines*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_guidelines.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubmissionGuidelinesDocumentDataSlicesSlice> /**
   * Meta Description field in *Submission Guidelines*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: submission_guidelines.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Submission Guidelines*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: submission_guidelines.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Submission Guidelines*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: submission_guidelines.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Submission Guidelines document from Prismic
 *
 * - **API ID**: `submission_guidelines`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubmissionGuidelinesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SubmissionGuidelinesDocumentData>,
    "submission_guidelines",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | AuthorsDocument
  | BlogPostsDocument
  | HomeDocument
  | SiteSettingsDocument
  | SubmissionGuidelinesDocument;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Hero - Left Aligned variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroCenteredPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Hero - Centered variation for Hero Slice
 *
 * - **API ID**: `heroCentered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroCentered = prismic.SharedSliceVariation<
  "heroCentered",
  Simplify<HeroSliceHeroCenteredPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroCentered;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AuthorsDocument,
      AuthorsDocumentData,
      BlogPostsDocument,
      BlogPostsDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      SiteSettingsDocument,
      SiteSettingsDocumentData,
      SiteSettingsDocumentDataEmailAddressesItem,
      SiteSettingsDocumentDataPhoneNumbersItem,
      SubmissionGuidelinesDocument,
      SubmissionGuidelinesDocumentData,
      SubmissionGuidelinesDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHeroCenteredPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroCentered,
    };
  }
}
