// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about: dynamic(() => import("./About")),
  founders: dynamic(() => import("./Founders")),
  guidelines: dynamic(() => import("./Guidelines")),
  hero: dynamic(() => import("./Hero")),
  message: dynamic(() => import("./Message")),
}
